version: "2"
run:
  timeout: 10m
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - errchkjson
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
formatters:
  enable:
    - gofmt
    - goimports
